#ifndef __SOC_CONTROL_HCL_DEF_H
#define __SOC_CONTROL_HCL_DEF_H

/* Includes ------------------------------------------------------------------*/
#include "../pulpissimo/pulpissimo.h"

/** @addtogroup PULPissimo_HCL_Driver
  * @{
  */

/** @addtogroup Peripheral_Registers_Bits_Definition
  * @{
  */

/******************************************************************************/
/*                         Peripheral Registers Bits Definition               */
/******************************************************************************/

/******************************************************************************/
/*                                                                            */
/*                           SoC Control (SOCCTRL)                            */
/*                                                                            */
/******************************************************************************/

/******************  Bit definition for SOCCTRL_INFO register  ****************/
#define SOCCTRL_INFO_NO_CLUSTERS_Pos    (0U)
#define SOCCTRL_INFO_NO_CLUSTERS_Msk    (0xFFFFUL << SOCCTRL_INFO_NO_CLUSTERS_Pos)
#define SOCCTRL_INFO_NO_CLUSTERS        SOCCTRL_INFO_NO_CLUSTERS_Msk
#define SOCCTRL_INFO_NO_CORES_Pos       (16U)
#define SOCCTRL_INFO_NO_CORES_Msk       (0xFFFFUL << SOCCTRL_INFO_NO_CORES_Pos)
#define SOCCTRL_INFO_NO_CORES           SOCCTRL_INFO_NO_CORES_Msk

/******************  Bit definition for SOCCTRL_PAD_MUX_0 register  ***********/
#define SOCCTRL_PAD_MUX_0_PADMUX0_Pos   (0U)
#define SOCCTRL_PAD_MUX_0_PADMUX0_Msk   (0x3UL << SOCCTRL_PAD_MUX_0_PADMUX0_Pos)
#define SOCCTRL_PAD_MUX_0_PADMUX0       SOCCTRL_PAD_MUX_0_PADMUX0_Msk
#define SOCCTRL_PAD_MUX_0_PADMUX1_Pos   (2U)
#define SOCCTRL_PAD_MUX_0_PADMUX1_Msk   (0x3UL << SOCCTRL_PAD_MUX_0_PADMUX1_Pos)
#define SOCCTRL_PAD_MUX_0_PADMUX1       SOCCTRL_PAD_MUX_0_PADMUX1_Msk
#define SOCCTRL_PAD_MUX_0_PADMUX2_Pos   (4U)
#define SOCCTRL_PAD_MUX_0_PADMUX2_Msk   (0x3UL << SOCCTRL_PAD_MUX_0_PADMUX2_Pos)
#define SOCCTRL_PAD_MUX_0_PADMUX2       SOCCTRL_PAD_MUX_0_PADMUX2_Msk
#define SOCCTRL_PAD_MUX_0_PADMUX3_Pos   (6U)
#define SOCCTRL_PAD_MUX_0_PADMUX3_Msk   (0x3UL << SOCCTRL_PAD_MUX_0_PADMUX3_Pos)
#define SOCCTRL_PAD_MUX_0_PADMUX3       SOCCTRL_PAD_MUX_0_PADMUX3_Msk
#define SOCCTRL_PAD_MUX_0_PADMUX4_Pos   (8U)
#define SOCCTRL_PAD_MUX_0_PADMUX4_Msk   (0x3UL << SOCCTRL_PAD_MUX_0_PADMUX4_Pos)
#define SOCCTRL_PAD_MUX_0_PADMUX4       SOCCTRL_PAD_MUX_0_PADMUX4_Msk
#define SOCCTRL_PAD_MUX_0_PADMUX5_Pos   (10U)
#define SOCCTRL_PAD_MUX_0_PADMUX5_Msk   (0x3UL << SOCCTRL_PAD_MUX_0_PADMUX5_Pos)
#define SOCCTRL_PAD_MUX_0_PADMUX5       SOCCTRL_PAD_MUX_0_PADMUX5_Msk
#define SOCCTRL_PAD_MUX_0_PADMUX6_Pos   (12U)
#define SOCCTRL_PAD_MUX_0_PADMUX6_Msk   (0x3UL << SOCCTRL_PAD_MUX_0_PADMUX6_Pos)
#define SOCCTRL_PAD_MUX_0_PADMUX6       SOCCTRL_PAD_MUX_0_PADMUX6_Msk
#define SOCCTRL_PAD_MUX_0_PADMUX7_Pos   (14U)
#define SOCCTRL_PAD_MUX_0_PADMUX7_Msk   (0x3UL << SOCCTRL_PAD_MUX_0_PADMUX7_Pos)
#define SOCCTRL_PAD_MUX_0_PADMUX7       SOCCTRL_PAD_MUX_0_PADMUX7_Msk
#define SOCCTRL_PAD_MUX_0_PADMUX8_Pos   (16U)
#define SOCCTRL_PAD_MUX_0_PADMUX8_Msk   (0x3UL << SOCCTRL_PAD_MUX_0_PADMUX8_Pos)
#define SOCCTRL_PAD_MUX_0_PADMUX8       SOCCTRL_PAD_MUX_0_PADMUX8_Msk
#define SOCCTRL_PAD_MUX_0_PADMUX9_Pos   (18U)
#define SOCCTRL_PAD_MUX_0_PADMUX9_Msk   (0x3UL << SOCCTRL_PAD_MUX_0_PADMUX9_Pos)
#define SOCCTRL_PAD_MUX_0_PADMUX9       SOCCTRL_PAD_MUX_0_PADMUX9_Msk
#define SOCCTRL_PAD_MUX_0_PADMUX10_Pos  (20U)
#define SOCCTRL_PAD_MUX_0_PADMUX10_Msk  (0x3UL << SOCCTRL_PAD_MUX_0_PADMUX10_Pos)
#define SOCCTRL_PAD_MUX_0_PADMUX10      SOCCTRL_PAD_MUX_0_PADMUX10_Msk
#define SOCCTRL_PAD_MUX_0_PADMUX11_Pos  (22U)
#define SOCCTRL_PAD_MUX_0_PADMUX11_Msk  (0x3UL << SOCCTRL_PAD_MUX_0_PADMUX11_Pos)
#define SOCCTRL_PAD_MUX_0_PADMUX11      SOCCTRL_PAD_MUX_0_PADMUX11_Msk
#define SOCCTRL_PAD_MUX_0_PADMUX12_Pos  (24U)
#define SOCCTRL_PAD_MUX_0_PADMUX12_Msk  (0x3UL << SOCCTRL_PAD_MUX_0_PADMUX12_Pos)
#define SOCCTRL_PAD_MUX_0_PADMUX12      SOCCTRL_PAD_MUX_0_PADMUX12_Msk
#define SOCCTRL_PAD_MUX_0_PADMUX13_Pos  (26U)
#define SOCCTRL_PAD_MUX_0_PADMUX13_Msk  (0x3UL << SOCCTRL_PAD_MUX_0_PADMUX13_Pos)
#define SOCCTRL_PAD_MUX_0_PADMUX13      SOCCTRL_PAD_MUX_0_PADMUX13_Msk
#define SOCCTRL_PAD_MUX_0_PADMUX14_Pos  (28U)
#define SOCCTRL_PAD_MUX_0_PADMUX14_Msk  (0x3UL << SOCCTRL_PAD_MUX_0_PADMUX14_Pos)
#define SOCCTRL_PAD_MUX_0_PADMUX14      SOCCTRL_PAD_MUX_0_PADMUX14_Msk
#define SOCCTRL_PAD_MUX_0_PADMUX15_Pos  (30U)
#define SOCCTRL_PAD_MUX_0_PADMUX15_Msk  (0x3UL << SOCCTRL_PAD_MUX_0_PADMUX15_Pos)
#define SOCCTRL_PAD_MUX_0_PADMUX15      SOCCTRL_PAD_MUX_0_PADMUX15_Msk

/******************  Bit definition for SOCCTRL_PAD_MUX_1 register  ***********/
#define SOCCTRL_PAD_MUX_1_PADMUX16_Pos   (0U)
#define SOCCTRL_PAD_MUX_1_PADMUX16_Msk   (0x3UL << SOCCTRL_PAD_MUX_1_PADMUX16_Pos)
#define SOCCTRL_PAD_MUX_1_PADMUX16       SOCCTRL_PAD_MUX_1_PADMUX16_Msk
#define SOCCTRL_PAD_MUX_1_PADMUX17_Pos   (2U)
#define SOCCTRL_PAD_MUX_1_PADMUX17_Msk   (0x3UL << SOCCTRL_PAD_MUX_1_PADMUX17_Pos)
#define SOCCTRL_PAD_MUX_1_PADMUX17       SOCCTRL_PAD_MUX_1_PADMUX17_Msk
#define SOCCTRL_PAD_MUX_1_PADMUX18_Pos   (4U)
#define SOCCTRL_PAD_MUX_1_PADMUX18_Msk   (0x3UL << SOCCTRL_PAD_MUX_1_PADMUX18_Pos)
#define SOCCTRL_PAD_MUX_1_PADMUX18       SOCCTRL_PAD_MUX_1_PADMUX18_Msk
#define SOCCTRL_PAD_MUX_1_PADMUX19_Pos   (6U)
#define SOCCTRL_PAD_MUX_1_PADMUX19_Msk   (0x3UL << SOCCTRL_PAD_MUX_1_PADMUX19_Pos)
#define SOCCTRL_PAD_MUX_1_PADMUX19       SOCCTRL_PAD_MUX_1_PADMUX19_Msk
#define SOCCTRL_PAD_MUX_1_PADMUX20_Pos   (8U)
#define SOCCTRL_PAD_MUX_1_PADMUX20_Msk   (0x3UL << SOCCTRL_PAD_MUX_1_PADMUX20_Pos)
#define SOCCTRL_PAD_MUX_1_PADMUX20       SOCCTRL_PAD_MUX_1_PADMUX20_Msk
#define SOCCTRL_PAD_MUX_1_PADMUX21_Pos   (10U)
#define SOCCTRL_PAD_MUX_1_PADMUX21_Msk   (0x3UL << SOCCTRL_PAD_MUX_1_PADMUX21_Pos)
#define SOCCTRL_PAD_MUX_1_PADMUX21       SOCCTRL_PAD_MUX_1_PADMUX21_Msk
#define SOCCTRL_PAD_MUX_1_PADMUX22_Pos   (12U)
#define SOCCTRL_PAD_MUX_1_PADMUX22_Msk   (0x3UL << SOCCTRL_PAD_MUX_1_PADMUX22_Pos)
#define SOCCTRL_PAD_MUX_1_PADMUX22       SOCCTRL_PAD_MUX_1_PADMUX22_Msk
#define SOCCTRL_PAD_MUX_1_PADMUX23_Pos   (14U)
#define SOCCTRL_PAD_MUX_1_PADMUX23_Msk   (0x3UL << SOCCTRL_PAD_MUX_1_PADMUX23_Pos)
#define SOCCTRL_PAD_MUX_1_PADMUX23       SOCCTRL_PAD_MUX_1_PADMUX23_Msk
#define SOCCTRL_PAD_MUX_1_PADMUX24_Pos   (16U)
#define SOCCTRL_PAD_MUX_1_PADMUX24_Msk   (0x3UL << SOCCTRL_PAD_MUX_1_PADMUX24_Pos)
#define SOCCTRL_PAD_MUX_1_PADMUX24       SOCCTRL_PAD_MUX_1_PADMUX24_Msk
#define SOCCTRL_PAD_MUX_1_PADMUX25_Pos   (18U)
#define SOCCTRL_PAD_MUX_1_PADMUX25_Msk   (0x3UL << SOCCTRL_PAD_MUX_1_PADMUX25_Pos)
#define SOCCTRL_PAD_MUX_1_PADMUX25       SOCCTRL_PAD_MUX_1_PADMUX25_Msk
#define SOCCTRL_PAD_MUX_1_PADMUX26_Pos   (20U)
#define SOCCTRL_PAD_MUX_1_PADMUX26_Msk   (0x3UL << SOCCTRL_PAD_MUX_1_PADMUX26_Pos)
#define SOCCTRL_PAD_MUX_1_PADMUX26       SOCCTRL_PAD_MUX_1_PADMUX26_Msk
#define SOCCTRL_PAD_MUX_1_PADMUX27_Pos   (22U)
#define SOCCTRL_PAD_MUX_1_PADMUX27_Msk   (0x3UL << SOCCTRL_PAD_MUX_1_PADMUX27_Pos)
#define SOCCTRL_PAD_MUX_1_PADMUX27       SOCCTRL_PAD_MUX_1_PADMUX27_Msk
#define SOCCTRL_PAD_MUX_1_PADMUX28_Pos   (24U)
#define SOCCTRL_PAD_MUX_1_PADMUX28_Msk   (0x3UL << SOCCTRL_PAD_MUX_1_PADMUX28_Pos)
#define SOCCTRL_PAD_MUX_1_PADMUX28       SOCCTRL_PAD_MUX_1_PADMUX28_Msk
#define SOCCTRL_PAD_MUX_1_PADMUX29_Pos   (26U)
#define SOCCTRL_PAD_MUX_1_PADMUX29_Msk   (0x3UL << SOCCTRL_PAD_MUX_1_PADMUX29_Pos)
#define SOCCTRL_PAD_MUX_1_PADMUX29       SOCCTRL_PAD_MUX_1_PADMUX29_Msk
#define SOCCTRL_PAD_MUX_1_PADMUX30_Pos   (28U)
#define SOCCTRL_PAD_MUX_1_PADMUX30_Msk   (0x3UL << SOCCTRL_PAD_MUX_1_PADMUX30_Pos)
#define SOCCTRL_PAD_MUX_1_PADMUX30       SOCCTRL_PAD_MUX_1_PADMUX30_Msk
#define SOCCTRL_PAD_MUX_1_PADMUX31_Pos   (30U)
#define SOCCTRL_PAD_MUX_1_PADMUX31_Msk   (0x3UL << SOCCTRL_PAD_MUX_1_PADMUX31_Pos)
#define SOCCTRL_PAD_MUX_1_PADMUX31       SOCCTRL_PAD_MUX_1_PADMUX31_Msk

/******************  Bit definition for SOCCTRL_PAD_MUX_2 register  ***********/
#define SOCCTRL_PAD_MUX_2_PADMUX32_Pos   (0U)
#define SOCCTRL_PAD_MUX_2_PADMUX32_Msk   (0x3UL << SOCCTRL_PAD_MUX_2_PADMUX32_Pos)
#define SOCCTRL_PAD_MUX_2_PADMUX32       SOCCTRL_PAD_MUX_2_PADMUX32_Msk
#define SOCCTRL_PAD_MUX_2_PADMUX33_Pos   (2U)
#define SOCCTRL_PAD_MUX_2_PADMUX33_Msk   (0x3UL << SOCCTRL_PAD_MUX_2_PADMUX33_Pos)
#define SOCCTRL_PAD_MUX_2_PADMUX33       SOCCTRL_PAD_MUX_2_PADMUX33_Msk
#define SOCCTRL_PAD_MUX_2_PADMUX34_Pos   (4U)
#define SOCCTRL_PAD_MUX_2_PADMUX34_Msk   (0x3UL << SOCCTRL_PAD_MUX_2_PADMUX34_Pos)
#define SOCCTRL_PAD_MUX_2_PADMUX34       SOCCTRL_PAD_MUX_2_PADMUX34_Msk
#define SOCCTRL_PAD_MUX_2_PADMUX35_Pos   (6U)
#define SOCCTRL_PAD_MUX_2_PADMUX35_Msk   (0x3UL << SOCCTRL_PAD_MUX_2_PADMUX35_Pos)
#define SOCCTRL_PAD_MUX_2_PADMUX35       SOCCTRL_PAD_MUX_2_PADMUX35_Msk
#define SOCCTRL_PAD_MUX_2_PADMUX36_Pos   (8U)
#define SOCCTRL_PAD_MUX_2_PADMUX36_Msk   (0x3UL << SOCCTRL_PAD_MUX_2_PADMUX36_Pos)
#define SOCCTRL_PAD_MUX_2_PADMUX36       SOCCTRL_PAD_MUX_2_PADMUX36_Msk
#define SOCCTRL_PAD_MUX_2_PADMUX37_Pos   (10U)
#define SOCCTRL_PAD_MUX_2_PADMUX37_Msk   (0x3UL << SOCCTRL_PAD_MUX_2_PADMUX37_Pos)
#define SOCCTRL_PAD_MUX_2_PADMUX37       SOCCTRL_PAD_MUX_2_PADMUX37_Msk
#define SOCCTRL_PAD_MUX_2_PADMUX38_Pos   (12U)
#define SOCCTRL_PAD_MUX_2_PADMUX38_Msk   (0x3UL << SOCCTRL_PAD_MUX_2_PADMUX38_Pos)
#define SOCCTRL_PAD_MUX_2_PADMUX38       SOCCTRL_PAD_MUX_2_PADMUX38_Msk
#define SOCCTRL_PAD_MUX_2_PADMUX39_Pos   (14U)
#define SOCCTRL_PAD_MUX_2_PADMUX39_Msk   (0x3UL << SOCCTRL_PAD_MUX_2_PADMUX39_Pos)
#define SOCCTRL_PAD_MUX_2_PADMUX39       SOCCTRL_PAD_MUX_2_PADMUX39_Msk
#define SOCCTRL_PAD_MUX_2_PADMUX40_Pos   (16U)
#define SOCCTRL_PAD_MUX_2_PADMUX40_Msk   (0x3UL << SOCCTRL_PAD_MUX_2_PADMUX40_Pos)
#define SOCCTRL_PAD_MUX_2_PADMUX40       SOCCTRL_PAD_MUX_2_PADMUX40_Msk
#define SOCCTRL_PAD_MUX_2_PADMUX41_Pos   (18U)
#define SOCCTRL_PAD_MUX_2_PADMUX41_Msk   (0x3UL << SOCCTRL_PAD_MUX_2_PADMUX41_Pos)
#define SOCCTRL_PAD_MUX_2_PADMUX41       SOCCTRL_PAD_MUX_2_PADMUX41_Msk
#define SOCCTRL_PAD_MUX_2_PADMUX42_Pos   (20U)
#define SOCCTRL_PAD_MUX_2_PADMUX42_Msk   (0x3UL << SOCCTRL_PAD_MUX_2_PADMUX42_Pos)
#define SOCCTRL_PAD_MUX_2_PADMUX42       SOCCTRL_PAD_MUX_2_PADMUX42_Msk
#define SOCCTRL_PAD_MUX_2_PADMUX43_Pos   (22U)
#define SOCCTRL_PAD_MUX_2_PADMUX43_Msk   (0x3UL << SOCCTRL_PAD_MUX_2_PADMUX43_Pos)
#define SOCCTRL_PAD_MUX_2_PADMUX43       SOCCTRL_PAD_MUX_2_PADMUX43_Msk
#define SOCCTRL_PAD_MUX_2_PADMUX44_Pos   (24U)
#define SOCCTRL_PAD_MUX_2_PADMUX44_Msk   (0x3UL << SOCCTRL_PAD_MUX_2_PADMUX44_Pos)
#define SOCCTRL_PAD_MUX_2_PADMUX44       SOCCTRL_PAD_MUX_2_PADMUX44_Msk
#define SOCCTRL_PAD_MUX_2_PADMUX45_Pos   (26U)
#define SOCCTRL_PAD_MUX_2_PADMUX45_Msk   (0x3UL << SOCCTRL_PAD_MUX_2_PADMUX45_Pos)
#define SOCCTRL_PAD_MUX_2_PADMUX45       SOCCTRL_PAD_MUX_2_PADMUX45_Msk
#define SOCCTRL_PAD_MUX_2_PADMUX46_Pos   (28U)
#define SOCCTRL_PAD_MUX_2_PADMUX46_Msk   (0x3UL << SOCCTRL_PAD_MUX_2_PADMUX46_Pos)
#define SOCCTRL_PAD_MUX_2_PADMUX46       SOCCTRL_PAD_MUX_2_PADMUX46_Msk
#define SOCCTRL_PAD_MUX_2_PADMUX47_Pos   (30U)
#define SOCCTRL_PAD_MUX_2_PADMUX47_Msk   (0x3UL << SOCCTRL_PAD_MUX_2_PADMUX47_Pos)
#define SOCCTRL_PAD_MUX_2_PADMUX47       SOCCTRL_PAD_MUX_2_PADMUX47_Msk

/******************  Bit definition for SOCCTRL_PAD_MUX_3 register  ***********/
#define SOCCTRL_PAD_MUX_3_PADMUX48_Pos   (0U)
#define SOCCTRL_PAD_MUX_3_PADMUX48_Msk   (0x3UL << SOCCTRL_PAD_MUX_3_PADMUX48_Pos)
#define SOCCTRL_PAD_MUX_3_PADMUX48       SOCCTRL_PAD_MUX_3_PADMUX48_Msk
#define SOCCTRL_PAD_MUX_3_PADMUX49_Pos   (2U)
#define SOCCTRL_PAD_MUX_3_PADMUX49_Msk   (0x3UL << SOCCTRL_PAD_MUX_3_PADMUX49_Pos)
#define SOCCTRL_PAD_MUX_3_PADMUX49       SOCCTRL_PAD_MUX_3_PADMUX49_Msk
#define SOCCTRL_PAD_MUX_3_PADMUX50_Pos   (4U)
#define SOCCTRL_PAD_MUX_3_PADMUX50_Msk   (0x3UL << SOCCTRL_PAD_MUX_3_PADMUX50_Pos)
#define SOCCTRL_PAD_MUX_3_PADMUX50       SOCCTRL_PAD_MUX_3_PADMUX50_Msk
#define SOCCTRL_PAD_MUX_3_PADMUX51_Pos   (6U)
#define SOCCTRL_PAD_MUX_3_PADMUX51_Msk   (0x3UL << SOCCTRL_PAD_MUX_3_PADMUX51_Pos)
#define SOCCTRL_PAD_MUX_3_PADMUX51       SOCCTRL_PAD_MUX_3_PADMUX51_Msk
#define SOCCTRL_PAD_MUX_3_PADMUX52_Pos   (8U)
#define SOCCTRL_PAD_MUX_3_PADMUX52_Msk   (0x3UL << SOCCTRL_PAD_MUX_3_PADMUX52_Pos)
#define SOCCTRL_PAD_MUX_3_PADMUX52       SOCCTRL_PAD_MUX_3_PADMUX52_Msk
#define SOCCTRL_PAD_MUX_3_PADMUX53_Pos   (10U)
#define SOCCTRL_PAD_MUX_3_PADMUX53_Msk   (0x3UL << SOCCTRL_PAD_MUX_3_PADMUX53_Pos)
#define SOCCTRL_PAD_MUX_3_PADMUX53       SOCCTRL_PAD_MUX_3_PADMUX53_Msk
#define SOCCTRL_PAD_MUX_3_PADMUX54_Pos   (12U)
#define SOCCTRL_PAD_MUX_3_PADMUX54_Msk   (0x3UL << SOCCTRL_PAD_MUX_3_PADMUX54_Pos)
#define SOCCTRL_PAD_MUX_3_PADMUX54       SOCCTRL_PAD_MUX_3_PADMUX54_Msk
#define SOCCTRL_PAD_MUX_3_PADMUX55_Pos   (14U)
#define SOCCTRL_PAD_MUX_3_PADMUX55_Msk   (0x3UL << SOCCTRL_PAD_MUX_3_PADMUX55_Pos)
#define SOCCTRL_PAD_MUX_3_PADMUX55       SOCCTRL_PAD_MUX_3_PADMUX55_Msk
#define SOCCTRL_PAD_MUX_3_PADMUX56_Pos   (16U)
#define SOCCTRL_PAD_MUX_3_PADMUX56_Msk   (0x3UL << SOCCTRL_PAD_MUX_3_PADMUX56_Pos)
#define SOCCTRL_PAD_MUX_3_PADMUX56       SOCCTRL_PAD_MUX_3_PADMUX56_Msk
#define SOCCTRL_PAD_MUX_3_PADMUX57_Pos   (18U)
#define SOCCTRL_PAD_MUX_3_PADMUX57_Msk   (0x3UL << SOCCTRL_PAD_MUX_3_PADMUX57_Pos)
#define SOCCTRL_PAD_MUX_3_PADMUX57       SOCCTRL_PAD_MUX_3_PADMUX57_Msk
#define SOCCTRL_PAD_MUX_3_PADMUX58_Pos   (20U)
#define SOCCTRL_PAD_MUX_3_PADMUX58_Msk   (0x3UL << SOCCTRL_PAD_MUX_3_PADMUX58_Pos)
#define SOCCTRL_PAD_MUX_3_PADMUX58       SOCCTRL_PAD_MUX_3_PADMUX58_Msk
#define SOCCTRL_PAD_MUX_3_PADMUX59_Pos   (22U)
#define SOCCTRL_PAD_MUX_3_PADMUX59_Msk   (0x3UL << SOCCTRL_PAD_MUX_3_PADMUX59_Pos)
#define SOCCTRL_PAD_MUX_3_PADMUX59       SOCCTRL_PAD_MUX_3_PADMUX59_Msk
#define SOCCTRL_PAD_MUX_3_PADMUX60_Pos   (24U)
#define SOCCTRL_PAD_MUX_3_PADMUX60_Msk   (0x3UL << SOCCTRL_PAD_MUX_3_PADMUX60_Pos)
#define SOCCTRL_PAD_MUX_3_PADMUX60       SOCCTRL_PAD_MUX_3_PADMUX60_Msk
#define SOCCTRL_PAD_MUX_3_PADMUX61_Pos   (26U)
#define SOCCTRL_PAD_MUX_3_PADMUX61_Msk   (0x3UL << SOCCTRL_PAD_MUX_3_PADMUX61_Pos)
#define SOCCTRL_PAD_MUX_3_PADMUX61       SOCCTRL_PAD_MUX_3_PADMUX61_Msk
#define SOCCTRL_PAD_MUX_3_PADMUX62_Pos   (28U)
#define SOCCTRL_PAD_MUX_3_PADMUX62_Msk   (0x3UL << SOCCTRL_PAD_MUX_3_PADMUX62_Pos)
#define SOCCTRL_PAD_MUX_3_PADMUX62       SOCCTRL_PAD_MUX_3_PADMUX62_Msk
#define SOCCTRL_PAD_MUX_3_PADMUX63_Pos   (30U)
#define SOCCTRL_PAD_MUX_3_PADMUX63_Msk   (0x3UL << SOCCTRL_PAD_MUX_3_PADMUX63_Pos)
#define SOCCTRL_PAD_MUX_3_PADMUX63       SOCCTRL_PAD_MUX_3_PADMUX63_Msk

/**
  * @}
  */


/**
  * @}
  */

#endif